### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by jrbenn** [logicly-au/docs.iar-dst.online#1]
headspace National Office (hNO) recently asked questions about using the IAR-DST API to collect the IAR-DST within hAPI.

In their initial query they were wanting an API that could accept the domain scores and give back a recommended level of care.
The two lines in the documentation at https://github.com/logicly-au/docs.iar-dst.online/blob/87f3728ff1ac483956c9c24930a6b12648b9540a/developers.rst?plain=1#L20-L21 make it sound like the IAR-DST API does this. It doesn't. OMSSS captures the domain scores from the user and then does the scoring. It doesn't allow the domain scores to be captured elsewhere and then provide a score.

**Comment by michellenSD** [comment]
@StratDatSi has suggested changing that to: `Provides a link to an IAR session that allows a user to submit the domain scores via the interface in the standard way;`

@adamc00, @jrbenn & @veryrusty will that address the issue?

**Comment by adamc00** [comment]
I've updated this to hopefully be more useful. I have further refined my words, and the whole list.

**Comment by michellenSD** [comment]
Closing, done
