### ISSUE TITLE
Other resources - Update resource name and document name

### ISSUE THREAD

**Issue by amymanunzio** [logicly-au/docs.iar-dst.online#18]
https://docs.iar-dst.online/en/v2/?_gl=1*1yy3p8k*_ga*MzMxNTU0NjY2LjE3MTY0MTI1NDE.*_ga_SDF1N6ZMM8*MTcxNjQxNjY3Ni40LjEuMTcxNjQyMTEwMy4wLjAuMA..#other-resources

The full name of each resource should be shown in the list, as follows:

- [x] Initial Assessment and Referral (IAR) Guidance for Mental Health Part A – General Guidance v2.0
- [x] Initial Assessment and Referral (IAR) Guidance for Mental Health Part B – Children v1.0 
- [x] Initial Assessment and Referral (IAR) Guidance for Mental Health Part C – Adolescents v1.0
- [x] Initial Assessment and Referral (IAR) Guidance for Mental Health Part D – Adults v2.0 
- [x] Initial Assessment and Referral (IAR) Guidance for Mental Health Part E – Older Adults v1.0

Will go back to the client about the last document listed online National MH-IAR Guidance V1.05 - 30 July.pdf

**Comment by adamc00** [comment]
> Will go back to the client about the last document listed

@amymanunzio, I suggest that we collaborate on that query. We can help them make smart choices by framing these queries appropriately.

**Comment by amymanunzio** [comment]
Tested and displaying as expected.

@LindaTarr when I download the documents the naming is "IAR Guidance Part B - Children - FINAL March 2024" - can we update the naming of the docs to match?

**Comment by amymanunzio** [comment]
New documents supplied by client and update as per https://github.com/logicly-au/docs.iar-dst.online/issues/23
