### ISSUE TITLE
Read more about this RLOC link displaying 404 error

### ISSUE THREAD

**Issue by amymanunzio** [logicly-au/docs.iar-dst.online#22]
Client reported when she clicks on the read more about this recommended level of care she gets the below 404 error. I haven't been able to replicate this.
![image](https://github.com/logicly-au/docs.iar-dst.online/assets/116606096/b02ceac6-6f1b-43d5-86f6-cb9b358b71a6)

Please let me know if we need further information.

Ref:
* [RT:12893783](https://rt.logicly.com.au/Transaction/Display.html?id=12893783)

**Comment by adamc00** [comment]
@amymanunzio, is the RT link there correct? I get an error trying to follow it.

**Comment by LogiclyLinda** [comment]
@amymanunzio I can't get the 404 on staging env. I can't see it in their emails, but have they mentioned if it's happening for a particular age bracket/level? Or are they getting it for every RLOC link?

**Comment by amymanunzio** [comment]
> @amymanunzio, is the RT link there correct? I get an error trying to follow it.

Updated link in initial comment

> @amymanunzio I can't get the 404 on staging env. I can't see it in their emails, but have they mentioned if it's happening for a particular age bracket/level? Or are they getting it for every RLOC link?

I can't replicate it on staging either @LindaTarr . The testing notes indicate they are testing for each age..

- Read more about this RLOC link directs to the relevant age group LOC description - FAIL
- Confirm each RLOC link directs to the updated wording that aligns with the new rating guides - FAIL

**Comment by amymanunzio** [comment]
Client tested this again and advised she no longer gets the error.
